services:
  php:
    build:
      dockerfile: php-dockerfile
      context: .
    image: backend-php
    container_name: backend-php
    restart: always
    ports:
      - '8080:80'
    networks:
      - internal
    volumes:
      - .:/home/backend/dev
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      #- ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini

  nginx:
      container_name: nginx
      image: nginx:latest
      ports:
          - 3000:80
      volumes:
          - ./src/:/usr/share/nginx/html/
          - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
          - ./logs/nginx:/var/log/nginx/
      links:
          - php
      networks:
      - internal

networks:
  internal:
    driver: bridge