services:
  php:
    build:
      dockerfile: php-dockerfile
      context: .
    image: backend-php
    container_name: php
    restart: always
    ports:
      - '9000:9000'
    volumes:
      - .:/home/app
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

  nginx:
      container_name: nginx
      image: nginx:alpine
      ports:
          - 3000:80
      volumes:
          - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
          - .:/home/app
          - ./logs/nginx:/var/log/nginx/
      links:
          - php